version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
      - "9090:9090"
      - "6060:6060"
    environment:
      - ENV_FILE=config.env
    restart: unless-stopped

  frontend:
    build:
      context: ./web_page
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped